name: Build images and push it to registries

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_PATH: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
      GHCR_IMAGE_PATH: ghcr.io/${{ github.repository }}
      IMAGE_VERSION_PREFIX: ''

    strategy:
      matrix:
        version:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata for pull requests
        if: github.event_name == 'pull_request'
        id: meta_pr
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE_PATH }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION_PREFIX }}pr${{ github.event.pull_request.number }}_${{ github.head_ref }}
            type=raw,value=${{ env.IMAGE_VERSION_PREFIX }}pr${{ github.event.pull_request.number }}_${{ github.sha }}

      - name: Extract image metadata for main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE_PATH }}
            ${{ env.GHCR_IMAGE_PATH }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION_PREFIX }}${{ matrix.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_BUILD_TOKEN }}

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
          tags: |
            ${{ steps.meta_pr.outputs.tags || steps.meta.outputs.tags }}

      - name: Add comment with image tag
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Docker images for this PR:
            ```bash
            ${{ steps.meta_pr.outputs.tags }}
            ```